// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	beerscli "github.com/CodelyTV/golang-examples/08-automated_tests/internal"
	mock "github.com/stretchr/testify/mock"
)

// StoreRepo is an autogenerated mock type for the StoreRepo type
type StoreRepo struct {
	mock.Mock
}

// GetStores provides a mock function with given fields:
func (_m *StoreRepo) GetStores() ([]beerscli.Store, error) {
	ret := _m.Called()

	var r0 []beerscli.Store
	if rf, ok := ret.Get(0).(func() []beerscli.Store); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]beerscli.Store)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
